version: 2
project_name: iso8583tool

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: iso8583tool
    ldflags:
      - -s -w -X github.com/nao1215/iso8583tool/cmd.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
