package main

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// skippedTapes are tapes this test deliberately does not replay, with the
// reason. demo-send.tape builds and backgrounds a mock acquirer, binds
// 127.0.0.1:18583 and leaves a process behind; replaying that here would put a
// port-binding race into the unit suite for no gain, because `iso8583tool send`
// against the same mock is already covered end to end by e2e/atago.
var skippedTapes = map[string]string{
	"demo-send.tape": "binds a TCP port and backgrounds a mock server; `send` is covered by e2e/atago",
}

// TestDemoTapesStillWork runs the commands each VHS tape types and requires the
// session to succeed.
//
// A GIF cannot be regenerated byte-for-byte (VHS output varies with timing,
// fonts and the encoder), so CI cannot diff it to prove the demos are current.
// What can be checked deterministically is the thing that actually rots: the
// command lines inside the tapes. Rename a subcommand or change a flag and this
// fails here, instead of the next `make demo` quietly recording five terminals
// full of usage errors -- `vhs` exits 0 no matter what appears on screen.
func TestDemoTapesStillWork(t *testing.T) { //nolint:paralleltest // the tapes share the /tmp fixtures the Makefile's demo target writes, so the cases run sequentially
	// The tapes are rendered on Linux by `make demo` and name POSIX paths
	// (/tmp/before.hex, /tmp/after.hex) literally, so replaying them elsewhere
	// would be testing the path syntax rather than the demo. The commands
	// themselves are covered on every platform by e2e/atago.
	if runtime.GOOS == "windows" {
		t.Skip("the tapes hardcode POSIX /tmp paths and are rendered on Linux")
	}

	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the tapes declare `Set Shell bash`")
	}
	binDir := buildToolForTape(t)
	prepareDiffFixtures(t, binDir)

	tapes, err := filepath.Glob(filepath.Join("docs", "*.tape"))
	if err != nil {
		t.Fatal(err)
	}
	if len(tapes) == 0 {
		t.Fatal("no tapes under docs/; the glob or the layout is wrong")
	}

	for _, tape := range tapes { //nolint:paralleltest // see the note on this test: the /tmp fixtures are shared
		t.Run(tape, func(t *testing.T) {
			if reason, ok := skippedTapes[filepath.Base(tape)]; ok {
				t.Skipf("not replayed: %s", reason)
			}

			script := shellLinesInTape(t, tape)
			if script == "" {
				t.Fatalf("%s types no commands; the tape or this parser is wrong", tape)
			}

			// The tapes run from the checkout root so that examples/... resolves,
			// which is also where `make demo` runs vhs from.
			cmd := exec.CommandContext(t.Context(), bash, "-e", "-c", script) //nolint:gosec // the script is read from a tape committed to this repository
			cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

			if out, err := cmd.CombinedOutput(); err != nil {
				t.Errorf("%s failed: %v\nscript:\n%s\noutput:\n%s", tape, err, script, out)
			}
		})
	}
}

// prepareDiffFixtures writes the /tmp/before.hex and /tmp/after.hex the diff
// tapes read, exactly as the Makefile's demo target does before running vhs.
func prepareDiffFixtures(t *testing.T, binDir string) {
	t.Helper()

	source := filepath.Join("examples", "basei", "0100-auth-request.hex")
	data, err := os.ReadFile(source) //nolint:gosec // a fixture inside the repository
	if err != nil {
		t.Fatal(err)
	}
	// The path is not this test's choice: the diff tapes name /tmp/before.hex
	// literally, so replaying them means writing where they read.
	if err := os.WriteFile("/tmp/before.hex", data, 0o600); err != nil { //nolint:gosec // the tape hardcodes this path
		t.Fatal(err)
	}

	// after.hex is before.hex with the PAN and amount changed, so the diff has
	// something to show. The Makefile does this with a convert | sed | convert
	// pipeline; the same substitution on the decoded form is enough here.
	tool := filepath.Join(binDir, "iso8583tool")
	decoded, err := exec.CommandContext(t.Context(), tool, "convert", source).Output() //nolint:gosec // a binary this test just built
	if err != nil {
		t.Fatalf("convert %s: %v", source, err)
	}
	changed := strings.NewReplacer(
		"4111111111111111", "4222222222222222",
		"000000005000", "000000009999",
	).Replace(string(decoded))

	encode := exec.CommandContext(t.Context(), tool, "convert") //nolint:gosec // a binary this test just built
	encode.Stdin = strings.NewReader(changed)
	out, err := encode.Output()
	if err != nil {
		t.Fatalf("re-encode the modified message: %v", err)
	}
	if err := os.WriteFile("/tmp/after.hex", out, 0o600); err != nil { //nolint:gosec // the tape hardcodes this path
		t.Fatal(err)
	}
}

// buildToolForTape builds the CLI and returns the directory holding it.
func buildToolForTape(t *testing.T) string {
	t.Helper()

	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("go toolchain not available; cannot build the binary the tapes drive")
	}
	binDir := t.TempDir()
	build := exec.CommandContext(context.Background(), goBin, "build", "-o", filepath.Join(binDir, "iso8583tool"), ".") //nolint:gosec // a fixed argv with a temp output path
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
	return binDir
}

// shellLinesInTape returns the commands a VHS tape types, in order, as one
// script. Lines typed between `Hide` and `Show` are the tape's own scaffolding
// -- they export a PATH and PS1 and clear the screen -- and the test supplies
// its own PATH, so they are skipped.
func shellLinesInTape(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path) //nolint:gosec // a test-supplied path inside the repository
	if err != nil {
		t.Fatal(err)
	}

	var lines []string
	hidden := false
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		switch line {
		case "Hide":
			hidden = true
			continue
		case "Show":
			hidden = false
			continue
		}
		if hidden || !strings.HasPrefix(line, `Type "`) {
			continue
		}
		typed := strings.TrimPrefix(line, `Type "`)
		end := strings.LastIndex(typed, `"`)
		if end < 0 {
			continue
		}
		lines = append(lines, strings.ReplaceAll(typed[:end], `\\`, `\`))
	}
	return strings.Join(lines, "\n")
}

// TestDemoTapesRenderTheDocumentedGIFs pins each tape's output path. A tape that
// renders somewhere else leaves the documentation showing a stale image with
// nothing failing.
func TestDemoTapesRenderTheDocumentedGIFs(t *testing.T) {
	t.Parallel()

	tapes, err := filepath.Glob(filepath.Join("docs", "*.tape"))
	if err != nil {
		t.Fatal(err)
	}
	for _, tape := range tapes {
		data, err := os.ReadFile(tape) //nolint:gosec // a test-supplied path inside the repository
		if err != nil {
			t.Fatal(err)
		}
		want := "Output docs/" + strings.TrimSuffix(filepath.Base(tape), ".tape") + ".gif"
		if !strings.Contains(string(data), want) {
			t.Errorf("%s does not %q", tape, want)
		}
	}
}
